version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: production
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./client
    ports:
      - "8080:80"
    environment:
      NODE_ENV: production

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
